### ISSUE TITLE
deck.gl zoom animation is behind Leaflet animation

### ISSUE THREAD

**Issue by zakjan** [zakjan/deck.gl-leaflet#1]
https://user-images.githubusercontent.com/173585/114974887-8be6df80-9e83-11eb-96cc-449c687f339a.mp4

See https://stackoverflow.com/questions/67101212/calculating-fractional-zoom-using-leaflet/67107000 for details.

**Comment by vissharm** [comment]
Is it not possible to hide the markers in zoom-start/drag-start and then show them back in zoom-end/drag-end ?

**Comment by zakjan** [comment]
Drag is fine, the issue is with zoom only, because Leaflet uses cubic-bezier transformation in CSS for zoom.

Hiding is possible, but in this integration case, Leaflet is the main library (with possibly other layers, not just markers), and deck.gl is only secondary. If I were to resort to hiding, I'd hide deck.gl layer instead.

**Comment by vissharm** [comment]
I din't get the part - DeckGL is secondary library. I think you whole purpose would be to create markers/polylines in the deckGL (deckGL objects) layer to improve performance by drawing with WebGL. Projections and its reverse is handled by DeckGL also. What benefit here leaflet providing???  want to understand?

**Comment by zakjan** [comment]
For a new project, it's surely better to start without Leaflet for the reasons you highlighted. The purpose of this library is 1) to allow enriching a pre-existing Leaflet application by adding a deck.gl visualization layer as easily as possible, and 2) potentially to support a step-by-step transition from Leaflet to deck.gl.

I'm going to explore the solution suggested in the SO link above in a couple of days.

**Comment by vissharm** [comment]
make sense

**Comment by zakjan** [comment]
Fixed in 1.1.0, thanks to the tips in the SO answer by @IvanSanchez.
