### ISSUE TITLE
Benchmark against existing Leaflet layers

### ISSUE THREAD

**Issue by charlieforward9** [zakjan/deck.gl-leaflet#12]
I used DeckGL with Google Maps about 2 years ago and am working on resuscitating this project. 

However, since then, I started working for a company that uses Leaflet, and has existing implementations that require 10k+ layers to display at the same time. The perforamnce of this is not great, and I was curious if:

1. This package is still being maintained
2. There is any existing comparisons of leaflet vs deckgl layers

Thank you for putting the time into such a helpful integration!

**Comment by zakjan** [comment]
Hi @charlieforward9, I suppose the bottleneck you're seeing is compositing DOM layers overlaid by WebGL layer. It's a known issue and will always be due to this combining different rendering approaches. This package exists for integration in simpler cases where migration away from Leaflet is not yet in scope. For better performance, I'd recommend to migrate to WebGL-only library, either deck.gl itself or deck.gl interleaved with MapLibre.

**Comment by zakjan** [comment]
More details about integrating with various base map libraries at https://deck.gl/docs/get-started/using-with-map

**Comment by charlieforward9** [comment]
@zakjan Thank you. To clarify, the Leaflet project currently does not use DeckGL. I used it on a separate project.

I am looking to improve our Leaflet setup with something GPU accelerated. Spent the whole day working on updating [Leaflet.glify](https://github.com/robertleeplummerjr/Leaflet.glify) since it impressed me with an impressive demo rendering 86 trillion points.

I realize that it is probably very similar to deck.gl-leaflet, but I don't know for sure... 

Do you have insight into which library I should prefer? (Keeping Leaflet for now unless I can understand why continuing is a bad idea)

My plan was to create a similar demo of both to test functional performances because I do not have a thorough understanding of the WebGL architecture.

DeckGL certainly offers more out of the box.

**Comment by zakjan** [comment]
Combining deck.gl and Leaflet is not recommended for high-performance use cases due to overlaying two canvases. The best for high-performance use cases is to use a single canvas in interleaved mode (deck.gl only or with Maplibre or another WebGL-based library).
