### ISSUE TITLE
LeafletLayer example for TS

### ISSUE THREAD

**Issue by sajcics** [zakjan/deck.gl-leaflet#14]
Hi
When I want to create LeafletLayer with a MapView, I get an type error 
`Type 'MapView[]' is not assignable to type 'null | undefined'.`

```js
 const deckGLlayer = new LeafletLayer({
          views: [new MapView({ repeat: true })], <--- this causes an issue
          layers: [
           ....
          ],
        });
```

as well, in the DeckProps it's mentioned that @default is MapView, is that means it doesn't need to be defined in LeafletLayer contructor as part of views property? 

dependencies:
- leaflet: 1.9.4.
- @deck.gl/core - tried with both 9.0.0 and as well 9.0.36
- deck.gl-leaflet 1.31.1

**Comment by zakjan** [comment]
Hi, thanks for the report. The fix is included in https://github.com/visgl/deck.gl-community/pull/179. Update @deck.gl-community/leaflet, please.
