### ISSUE TITLE
Supporting mouse events in Deck layers

### ISSUE THREAD

**Issue by NRaf** [zakjan/deck.gl-leaflet#2]
Great work on this library, has made it really easy to get started with Deck!

I noticed you have `pointer-events: none` as well as `controller: false`, preventing the deck layers from being able to respond to user input. In my case, I have an `onHover` function on a bitmap layer I'm using to get the color as a specific location.

We're there any plans to make this configurable for such use cases? Have you experienced any issues with allowing the mouse events to flow through to Deck?

**Comment by zakjan** [comment]
Thanks! Your comments were very helpful for bringing this library to life.

Yes, I'm going to improve the mouse interactions and picking support further, following the patterns in other existing integration libraries.

**Comment by arthurgailes** [comment]
Do you have any interim guidance on this? I'd love to use it in my work, but can't without interactivity.

**Comment by zakjan** [comment]
I gave it a shot and it seems it's working. I'm not sure why I used `pointer-events: none` in the first place. Released as 1.2.0. Let me know if it works for you.
