### ISSUE TITLE
Objects jump on zoom change

### ISSUE THREAD

**Issue by DmitriyVTitov** [zakjan/deck.gl-leaflet#4]
It's something like https://github.com/visgl/deck.gl/issues/5588 I think.
I'm using deck.gl-leaflet with Vue-Leaflet application and facing the problem that objects on map jumps when I change zoom level.
I've unexpirienced JS dev and bootstrapped sample application with provided example code
```
<script>
import { MapView } from "@deck.gl/core"
import map from "@/mixins/map"
import { ArcLayer, GeoJsonLayer } from "@deck.gl/layers"
import { LeafletLayer } from "deck.gl-leaflet"

export default {
  name: "AdminLayout",
  mixins: [map],
  data() {
    return {
      center: [30, 50],
      zoom: 4
    }
  },
  mounted() {
    const AIR_PORTS =
      "https://d2ad6b4ur7yvpq.cloudfront.net/naturalearth-3.3.0/ne_10m_airports.geojson"
    const deckLayer = new LeafletLayer({
      views: [
        new MapView({
          repeat: true
        })
      ],
      layers: [
        new GeoJsonLayer({
          id: "airports",
          data: AIR_PORTS,
          // Styles
          filled: true,
          pointRadiusMinPixels: 2,
          pointRadiusScale: 2000,
          getPointRadius: f => 11 - f.properties.scalerank,
          getFillColor: [200, 0, 80, 180]
        }),
        new ArcLayer({
          id: "arcs",
          data: AIR_PORTS,
          dataTransform: d => d.features.filter(f => f.properties.scalerank < 4),
          // Styles
          getSourcePosition: f => [-0.4531566, 51.4709959], // London
          getTargetPosition: f => f.geometry.coordinates,
          getSourceColor: [0, 128, 200],
          getTargetColor: [200, 0, 80],
          getWidth: 1
        })
      ]
    })
    this.$nextTick(() => {
      this.$refs.map.mapObject.addLayer(deckLayer)
    })
  },
  methods: {
  }
}
</script>
```

The code is from here:
https://github.com/visgl/deck.gl/blob/8.5-release/examples/get-started/pure-js/leaflet/app.js

I understand this is not a Vue plugin, but can you give me a clue where should I look?

**Comment by DmitriyVTitov** [comment]
It's latest versions.

    "@deck.gl/core": "^8.5.3",
    "@deck.gl/layers": "^8.5.3",
    "deck.gl-leaflet": "^1.1.2",

**Comment by zakjan** [comment]
Hi @DmitriyVTitov, can you publish a codepen replicating the bug?

**Comment by DmitriyVTitov** [comment]
@zakjan No, it's almost impossible, because App uses mixins.
I will try to create minimum app with vue-leaflet and your library tomorrow and copy that to codepen.

**Comment by DmitriyVTitov** [comment]
@zakjan Your plugin works very well on clean app. Something interferred with one of our mixins so false alarm :)
Close the issue pls.

**Comment by zakjan** [comment]
Perfect, thanks for confirming!
