### ISSUE TITLE
Can I use the 3D perspective of deck.gl while using this library?

### ISSUE THREAD

**Issue by ramuyk** [zakjan/deck.gl-leaflet#5]
Hi

I've made some tests with this library and I understood that I can can create deck.gl layers on a Leaflet map. However, it's not clear to me if the 3D perspective from deck.gl is possible to use with this library. Is it possible to do? Or the only way of using the 3D perspective would be using deck.gl without integrating it with Leaflet? 

It's a conceptual doubt only... The advantage of using this library would be being capable of creating layers that deck.gl can make and Leaflet can't, is that so? I'd like to understand the benefits and limitations of using it so far if possible...

**Comment by zakjan** [comment]
Hi, you're right. This plugin enables to add deck.gl layers on top of Leaflet basemaps, i.e. no 3D.

**Comment by ramuyk** [comment]
Cool, in case I'm creating simple layers with polygons, polylines and points... Is there any difference in performance? I mean, Leaflet cannot create layers with a lot of data on it... When I use a deck.gl layer on a Leaflet map with this plugin is it going to have a better performance? Or is it converting the deck.gl layer to a Leaflet layer?

**Comment by zakjan** [comment]
The difference is in the underlying rendering technology. I don't have exact numbers at hand, but Leaflet uses SVG by default, or you can opt-in for Canvas. deck.gl uses GPU-accelerated WebGL rendering, which can scale to even larger number of features.

**Comment by ramuyk** [comment]
I see... So when using this plugin, the deck.gl layers that are created are still using GPU-accelerated WebGL rendering? Even though it's being created on top of a Leaflet map?

**Comment by zakjan** [comment]
Exactly, this plugin allows to create a deck.gl context as a Leaflet layer, and render on top of Leaflet basemap, for the purpose of adding deck.gl layers to an previously existing Leaflet application.

For a new application, it's usually better to use deck.gl directly for basemap tiles as well.
