### ISSUE TITLE
tooltips should be on top level

### ISSUE THREAD

**Issue by wlbksy** [zakjan/deck.gl-leaflet#6]
![image](https://user-images.githubusercontent.com/2433806/156720795-662da749-4b7f-44d9-ad4b-772ac910b67e.png)

**Comment by zakjan** [comment]
Hi, thanks for the report. I can replicate it, I'll take a look.

**Comment by zakjan** [comment]
Fixed in https://github.com/zakjan/deck.gl-leaflet/commit/2fd5157fd58164c7c8841164d525ffb13de9869d, released as 1.2.1

**Comment by wlbksy** [comment]
Thanks!
